Typing cleanup
turnkeylinux/turnkey-version pull request #6
Opened 2023-06-03 23:07 UTC by JedMeister

More turd polishing...

2023-06-05 23:21 UTC, Christie018 approved these changes
Code changes look good to me 😃

2023-06-07 00:55 UTC, OnGle approved these changes
lgtm!

2023-06-07 00:55 UTC, OnGle commented on sysversion/__init__.py
> +        raise TurnkeyVersionError("lsb_release failed: {proc}'")
fstring missing the f

2023-06-07 00:56 UTC, OnGle requested changes
My mistake, accidently approved with "lgtm" but that f-string should be fixed

2023-06-15 05:22 UTC, JedMeister commented on sysversion/__init__.py
> +        raise TurnkeyVersionError("lsb_release failed: {proc}'")
Good catch, thanks!

2023-06-15 05:24 UTC, JedMeister commented
Issue fixed. Merging...

2023-06-15 05:24 UTC, merged